// GENERATED by scripts/build-shift-alerts.mjs from main.ts and the app's src/core and src/data: do not edit; run npm run functions:build.
// supabase/functions/shift-alerts/main.ts
import webpush from "npm:web-push@3";

// src/core/roster/index.ts
var MORNING_ORDER = ["B", "C", "A", "D"];
var ANCHOR_DATE = "2026-03-02";
var DAY_MS = 864e5;
var STATE_BY_OFFSET = ["M", "Off", "N", "A"];
function utc(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return Date.UTC(y, m - 1, d);
}
var ANCHOR_MS = utc(ANCHOR_DATE);
function daysFromAnchor(date) {
  return Math.round((utc(date) - ANCHOR_MS) / DAY_MS);
}
function morningCrew(date) {
  const n = daysFromAnchor(date);
  const block = Math.floor(n / 2);
  return MORNING_ORDER[(block % 4 + 4) % 4];
}
function dutyFor(date, crew) {
  const n = daysFromAnchor(date);
  const dayInBlock = (n % 2 + 2) % 2 + 1;
  const mi = MORNING_ORDER.indexOf(morningCrew(date));
  const offset = (MORNING_ORDER.indexOf(crew) - mi + 4) % 4;
  return `${STATE_BY_OFFSET[offset]}${dayInBlock}`;
}
function stateOf(duty) {
  return duty.startsWith("Off") ? "Off" : duty[0];
}
var CREWS = ["A", "B", "C", "D"];
var SHIFT_LABEL = { M: "Morning", A: "Afternoon", N: "Night", Off: "Off" };
function dutyLabel(duty) {
  const s = stateOf(duty);
  return s === "Off" ? `Off ${duty.slice(3)}` : `${SHIFT_LABEL[s]} ${duty}`;
}
function addDaysIso(iso, days) {
  const d = /* @__PURE__ */ new Date(iso + "T00:00:00Z");
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}
function crewsByShift(date) {
  const out = {};
  for (const c of CREWS) out[stateOf(dutyFor(date, c))] = c;
  return out;
}

// src/core/manpower/index.ts
var SD_TEAM = "SD";
var DAY_DUTY = "DAY";
var isDayDutyWorkday = (date) => (/* @__PURE__ */ new Date(date + "T00:00:00Z")).getUTCDay() <= 4;
var CREW_ROLES = ["controller", "panel_operator", "field_operator"];
function personOn(p, date) {
  let role = p.role, crew = p.crew;
  if (p.history?.length) {
    const h = [...p.history].sort((a, b) => a.from.localeCompare(b.from));
    const period = h.find((x) => x.from <= date && (x.to === null || date <= x.to)) ?? (date < h[0].from ? h[0] : h[h.length - 1]);
    role = period.role;
    crew = period.crew;
  }
  const on = (m) => m.start <= date && (m.end === null || date <= m.end);
  if (role === "vr_controller") {
    const placed = p.moves?.find((m) => m.kind === "placement" && on(m) && m.crew !== DAY_DUTY);
    const vrCrew = placed ? placed.crew : null;
    return role === p.role && vrCrew === p.crew && !p.movedFrom && !p.dayDuty ? p : { ...p, role, crew: vrCrew, movedFrom: void 0, dayDuty: void 0 };
  }
  const move = crew && CREW_ROLES.includes(role) ? p.moves?.find((m) => m.kind !== "placement" && on(m) && m.crew !== crew) : void 0;
  if (move) return move.crew === DAY_DUTY ? { ...p, role, crew: null, movedFrom: crew, dayDuty: true } : move.crew === SD_TEAM ? { ...p, role, crew: null, movedFrom: crew, dayDuty: void 0, sdTeam: true } : { ...p, role, crew: move.crew, movedFrom: crew, dayDuty: void 0 };
  return role === p.role && crew === p.crew && !p.movedFrom && !p.dayDuty && !p.sdTeam ? p : { ...p, role, crew, movedFrom: void 0, dayDuty: void 0, sdTeam: void 0 };
}
var FULL_OPERATION = {
  modeCode: "full_operation",
  modeLabel: "Full operation",
  controllerMin: 1,
  controllerGrade: 15,
  actingControllerGrade: 14,
  panelMin: 3,
  panelGrade14Min: 1,
  panelGrade14: 14,
  fieldMin: 6,
  panelBackupGrade: 13,
  controllerGreenAtMinimum: true
};
var PENDING_FINDINGS = ["data_incomplete", "coverage_required"];
var rulesOn = (src, date) => typeof src === "function" ? src(date) : src;
var SHIFT_ORDER = ["M", "A", "N", "Off"];
var RANK = { green: 0, amber: 1, red: 2 };
var worst = (list) => list.reduce((w, s) => RANK[s] > RANK[w] ? s : w, "green");
function statusFor(count, min) {
  return count > min ? "green" : count === min ? "amber" : "red";
}
var isUnknown = (q) => q !== "yes" && q !== "no";
function finishPosition(base) {
  const { requirementMet, potentialMet, coverage, greenAtMinimum, ...rest } = base;
  const rate = (count) => greenAtMinimum && count >= base.min ? "green" : statusFor(count, base.min);
  const status = !requirementMet ? "red" : rate(base.count);
  let finding;
  let provisionalStatus;
  if (requirementMet) {
    finding = base.count > base.min ? "above_minimum" : status === "green" ? "staffed" : "no_buffer";
    provisionalStatus = status;
  } else if (coverage) {
    finding = "coverage_required";
    provisionalStatus = rate(base.min);
  } else if (potentialMet) {
    finding = "data_incomplete";
    provisionalStatus = rate(base.potential);
  } else {
    finding = "shortage";
    provisionalStatus = "red";
  }
  return { ...rest, status, finding, final: !PENDING_FINDINGS.includes(finding), provisionalStatus };
}
var covers = (a, date) => a.start <= date && date <= a.end;
var isLeave = (a) => (a.status === "approved" || a.status === "planned") && a.inCurrentPlan !== false;
var isUnresolved = (a) => a.status === "unresolved" && a.inCurrentPlan !== false;
var gradeText = (p) => p.grade == null ? "grade not recorded" : `Grade ${p.grade}`;
function qualReason(label, s) {
  return s === "no" ? `${label} = No` : s === "not_yet_confirmed" ? `${label} not yet confirmed` : `${label} not recorded`;
}
function evaluateDay(date, allPeople, absences, rulesSource = FULL_OPERATION, assignments = []) {
  const rules = rulesOn(rulesSource, date);
  const morningCrew2 = CREWS.find((c) => stateOf(dutyFor(date, c)) === "M") ?? null;
  const dayDutyCrew = isDayDutyWorkday(date) ? morningCrew2 : null;
  const people = allPeople.map((p) => personOn(p, date)).map((p) => p.dayDuty && dayDutyCrew ? { ...p, crew: dayDutyCrew } : p);
  const todays = assignments.filter((a) => a.start <= date && date <= a.end);
  const assignmentOf = (p) => todays.find((a) => a.employeeId === p.id && a.kind !== "sd_team") ?? todays.find((a) => a.employeeId === p.id) ?? null;
  const byId = new Map(people.map((p) => [p.id, p]));
  const byEmp = /* @__PURE__ */ new Map();
  for (const a of absences) if (covers(a, date)) {
    const l = byEmp.get(a.employeeId) ?? [];
    l.push(a);
    byEmp.set(a.employeeId, l);
  }
  const leaveOf = (p) => (byEmp.get(p.id) ?? []).find(isLeave) ?? null;
  const unresolvedOf = (p) => (byEmp.get(p.id) ?? []).find(isUnresolved) ?? null;
  const crews = CREWS.map((crew) => {
    const duty = dutyFor(date, crew);
    const state = stateOf(duty);
    const working = state !== "Off";
    const members = people.filter((p) => p.crew === crew && (p.role === "controller" || p.role === "vr_controller" || p.role === "panel_operator" || p.role === "field_operator"));
    const absencesOnDay = [];
    const unresolved = [];
    const available = [];
    const away = [];
    for (const p of members) {
      const leave = leaveOf(p);
      const unres = unresolvedOf(p);
      const own = assignmentOf(p);
      const assigned = (p.role === "controller" || p.role === "vr_controller") && own && !(own.kind === "shift_cover" && own.crew === crew) ? own : null;
      if (leave) absencesOnDay.push({ person: p, absence: leave, reducesManpower: working });
      if (unres) unresolved.push({ person: p, absence: unres, reducesManpower: false });
      if (assigned && working && !leave) {
        away.push({ person: p, assignment: assigned });
        continue;
      }
      if (!leave || !working) available.push(p);
    }
    const ctrlCounted = [];
    const ctrlNot = [];
    const ctrlIssues = [];
    let acting = null;
    const qualifiesAsController = (p) => p.grade != null && p.grade >= rules.controllerGrade || p.grade != null && p.grade >= rules.actingControllerGrade && p.actingController === "yes";
    for (const p of available.filter((x) => x.role === "controller" || x.role === "vr_controller")) {
      if (p.grade != null && p.grade >= rules.controllerGrade) ctrlCounted.push(p);
      else if (p.grade != null && p.grade >= rules.actingControllerGrade && p.actingController === "yes") {
        ctrlCounted.push(p);
        acting ??= p;
      } else ctrlNot.push({ person: p, pendingData: p.grade == null, reason: `${gradeText(p)}; Controller needs Grade ${rules.controllerGrade}+ or a recorded Grade-${rules.actingControllerGrade} Acting Controller qualification` });
    }
    const pool = { panel: available.filter((x) => x.role === "panel_operator"), field: available.filter((x) => x.role === "field_operator") };
    const coverAssignment = todays.find((a) => a.kind === "shift_cover" && a.crew === crew) ?? null;
    const coverPerson = coverAssignment ? byId.get(coverAssignment.employeeId) ?? null : null;
    let cover = null;
    if (coverAssignment && coverPerson) {
      const absence = leaveOf(coverPerson);
      const counted = working && !absence && coverPerson.grade != null && coverPerson.grade >= rules.controllerGrade;
      cover = { person: coverPerson, assignment: coverAssignment, counted, absence };
      if (counted && !ctrlCounted.includes(coverPerson)) ctrlCounted.push(coverPerson);
    }
    if (ctrlCounted.length < rules.controllerMin) {
      const canAct = (p) => p.grade != null && p.grade >= rules.actingControllerGrade && p.grade < rules.controllerGrade && p.actingController === "yes";
      const panelBuffer = pool.panel.filter((p) => p.panelQualified === "yes").length - rules.panelMin;
      const fieldBuffer = pool.field.filter((p) => p.takeCharge === "yes").length - rules.fieldMin;
      const order = fieldBuffer > panelBuffer ? ["field", "panel"] : ["panel", "field"];
      for (const k of order) {
        const c = pool[k].find(canAct);
        if (c) {
          acting = c;
          ctrlCounted.push(c);
          pool[k] = pool[k].filter((p) => p !== c);
          break;
        }
      }
    }
    if (acting) ctrlIssues.push(`Acting Controller: ${acting.name} (Grade ${acting.grade})`);
    if (cover?.counted) ctrlIssues.push(`Covered by ${cover.person.name}`);
    const ctrlOnLeave = working ? members.filter((p) => p.role === "controller" && leaveOf(p) && qualifiesAsController(p)) : [];
    const ctrlCount = ctrlCounted.length;
    const ctrlMet = ctrlCount >= rules.controllerMin;
    const ctrlCoverage = !ctrlMet && (ctrlOnLeave.length > 0 || away.length > 0 || cover !== null && !cover.counted);
    const ctrlPotentialMet = ctrlCount + ctrlNot.filter((n) => n.pendingData).length >= rules.controllerMin;
    if (ctrlCoverage) {
      const why = [...ctrlOnLeave.map((p) => `${p.name} (${leaveOf(p)?.typeLabel ?? "leave"})`), ...away.map((w) => `${w.person.name} (${w.assignment.kind === "morning_rotation" ? "Morning rotation" : w.assignment.kind === "sd_team" ? "shutdown team" : `covering ${w.assignment.crew} Shift`})`)];
      ctrlIssues.push(`Controller coverage required: ${why.join(", ")}${cover && !cover.counted ? ` — recorded cover ${cover.person.name} is ${cover.absence ? "on leave" : "not Grade " + rules.controllerGrade + "+"}` : " — no cover recorded"}`);
    } else if (!ctrlMet && ctrlPotentialMet) ctrlIssues.push("Controller grade not recorded");
    else if (!ctrlMet) ctrlIssues.push(`Confirmed shortage: Controller ${ctrlCount} of ${rules.controllerMin} required`);
    const controller = {
      ...finishPosition({
        key: "controller",
        label: "Controller",
        count: ctrlCount,
        min: rules.controllerMin,
        buffer: ctrlCount - rules.controllerMin,
        potential: ctrlCount + ctrlNot.filter((n) => n.pendingData).length,
        counted: ctrlCounted,
        notCounted: ctrlNot,
        issues: ctrlIssues,
        requirementMet: ctrlMet,
        potentialMet: ctrlPotentialMet,
        coverage: ctrlCoverage,
        greenAtMinimum: rules.controllerGreenAtMinimum
      }),
      acting,
      onLeave: ctrlOnLeave,
      away,
      cover
    };
    const fromField = [];
    {
      const qualified = pool.panel.filter((p) => p.panelQualified === "yes").length;
      let fieldSpare = pool.field.filter((p) => p.takeCharge === "yes").length - rules.fieldMin;
      for (const c of pool.field.filter((p) => p.grade != null && p.grade >= rules.panelBackupGrade).sort((a, b) => (b.grade ?? 0) - (a.grade ?? 0) || a.name.localeCompare(b.name))) {
        if (qualified + fromField.length >= rules.panelMin) break;
        if (c.takeCharge === "yes") {
          if (fieldSpare <= 0) continue;
          fieldSpare--;
        }
        fromField.push(c);
      }
      pool.field = pool.field.filter((p) => !fromField.includes(p));
    }
    const panelCounted = [...pool.panel.filter((p) => p.panelQualified === "yes"), ...fromField];
    const panelNot = pool.panel.filter((p) => p.panelQualified !== "yes").map((p) => ({ person: p, pendingData: isUnknown(p.panelQualified), reason: qualReason("Panel qualification", p.panelQualified) }));
    const isG14 = (p) => p.grade != null && p.grade >= rules.panelGrade14;
    const g14Unknown = (p) => p.grade == null && p.employmentType === "knpc";
    const grade14 = panelCounted.filter(isG14).length;
    const panelPotentialPeople = [...panelCounted, ...pool.panel.filter((p) => isUnknown(p.panelQualified))];
    const potentialGrade14 = panelPotentialPeople.filter((p) => isG14(p) || g14Unknown(p)).length;
    const panelMet = panelCounted.length >= rules.panelMin && grade14 >= rules.panelGrade14Min;
    const panelPotentialMet = panelPotentialPeople.length >= rules.panelMin && potentialGrade14 >= rules.panelGrade14Min;
    const panelIssues = [];
    if (!panelMet) {
      const what = [panelCounted.length < rules.panelMin ? `${panelCounted.length}/${rules.panelMin} qualified` : null, grade14 < rules.panelGrade14Min ? `no Grade ${rules.panelGrade14}+ Panel Operator` : null].filter(Boolean).join(", ");
      const short = [panelCounted.length < rules.panelMin ? `${panelCounted.length} of ${rules.panelMin} required` : null, grade14 < rules.panelGrade14Min ? `no Grade ${rules.panelGrade14}+ Panel Operator available` : null].filter(Boolean).join(", ");
      panelIssues.push(panelPotentialMet ? `Panel qualification data incomplete: ${what} confirmed` : `Confirmed shortage: Panel ${short}`);
    }
    const fieldTakeCharge = pool.field.filter((p) => p.takeCharge === "yes");
    const backup = panelMet && panelCounted.length === rules.panelMin ? pool.field.filter((p) => p.grade != null && p.grade >= rules.panelBackupGrade && (!fieldTakeCharge.includes(p) || fieldTakeCharge.length - 1 >= rules.fieldMin)).sort((a, b) => (b.grade ?? 0) - (a.grade ?? 0) || a.name.localeCompare(b.name))[0] ?? null : null;
    for (const p of fromField) panelIssues.push(`Filled from Field: ${p.name} (Grade ${p.grade})`);
    if (backup) panelIssues.push(`Buffer: ${backup.name} (Field Operator, Grade ${backup.grade}) can take a Panel seat`);
    const panel = {
      ...finishPosition({
        key: "panel",
        label: "Panel",
        count: panelCounted.length,
        min: rules.panelMin,
        buffer: panelCounted.length - rules.panelMin + (backup ? 1 : 0),
        potential: panelPotentialPeople.length,
        counted: panelCounted,
        notCounted: panelNot,
        issues: panelIssues,
        requirementMet: panelMet,
        potentialMet: panelPotentialMet,
        greenAtMinimum: backup !== null
      }),
      grade14,
      potentialGrade14,
      backup,
      fromField
    };
    const fieldCounted = pool.field.filter((p) => p.takeCharge === "yes");
    const fieldNot = pool.field.filter((p) => p.takeCharge !== "yes").map((p) => ({ person: p, pendingData: isUnknown(p.takeCharge), reason: qualReason("Take-Charge", p.takeCharge) }));
    const fieldUnknown = fieldNot.filter((n) => n.pendingData).length;
    const fieldPotential = fieldCounted.length + fieldUnknown;
    const fieldMet = fieldCounted.length >= rules.fieldMin;
    const fieldPotentialMet = fieldPotential >= rules.fieldMin;
    const fieldIssues = [];
    if (!fieldMet) fieldIssues.push(fieldPotentialMet ? `Take-Charge data incomplete: ${fieldCounted.length}/${rules.fieldMin} confirmed, ${fieldUnknown} not yet confirmed (up to ${fieldPotential}/${rules.fieldMin} if confirmed)` : `Confirmed shortage: Field ${fieldCounted.length} of ${rules.fieldMin} required${fieldUnknown ? ` (at most ${fieldPotential} even if all unconfirmed are confirmed)` : ""}`);
    const fieldBackup = fieldMet && fieldCounted.length === rules.fieldMin && panelMet && panelCounted.length > rules.panelMin ? panelCounted.filter((p) => p.grade != null && p.grade >= rules.panelBackupGrade && grade14 - (isG14(p) ? 1 : 0) >= rules.panelGrade14Min).sort((a, b) => (a.grade ?? 0) - (b.grade ?? 0) || a.name.localeCompare(b.name))[0] ?? null : null;
    if (fieldBackup) fieldIssues.push(`Buffer: ${fieldBackup.name} (Panel Operator, Grade ${fieldBackup.grade}) can take a Field post`);
    const field = { ...finishPosition({
      key: "field",
      label: "Field",
      count: fieldCounted.length,
      min: rules.fieldMin,
      buffer: fieldCounted.length - rules.fieldMin + (fieldBackup ? 1 : 0),
      potential: fieldPotential,
      counted: fieldCounted,
      notCounted: fieldNot,
      issues: fieldIssues,
      requirementMet: fieldMet,
      potentialMet: fieldPotentialMet,
      greenAtMinimum: fieldBackup !== null
    }), backup: fieldBackup };
    const positions = [controller, panel, field];
    const status = working ? worst(positions.map((p) => p.status)) : null;
    const confirmedShortage = working && positions.some((p) => p.finding === "shortage");
    const pending = working ? [...new Set(positions.filter((p) => !p.final).map((p) => p.finding))] : [];
    const provisionalStatus2 = working ? worst(positions.map((p) => p.provisionalStatus)) : null;
    const finalStatus2 = !working ? null : confirmedShortage ? "red" : pending.length ? null : status;
    return {
      crew,
      duty,
      state,
      shift: SHIFT_LABEL[state],
      dutyLabel: dutyLabel(duty),
      working,
      status,
      finalStatus: finalStatus2,
      provisionalStatus: provisionalStatus2,
      pending,
      confirmedShortage,
      noBuffer: finalStatus2 === "amber",
      controller,
      panel,
      field,
      absences: absencesOnDay,
      unresolved,
      members: members.length
    };
  }).sort((a, b) => SHIFT_ORDER.indexOf(a.state) - SHIFT_ORDER.indexOf(b.state));
  const rotation = todays.find((a) => a.kind === "morning_rotation") ?? null;
  const dayStaff = people.filter((p) => p.role === "vr_controller" || p.role === "morning_controller" || p.id === rotation?.employeeId).map((p) => ({
    person: p,
    absence: leaveOf(p),
    unresolved: unresolvedOf(p),
    assignment: assignmentOf(p),
    morningPost: rotation ? p.id === rotation.employeeId : p.role === "morning_controller"
  }));
  const dayDuty = people.filter((p) => p.dayDuty).map((p) => ({ person: p, absence: leaveOf(p), unresolved: unresolvedOf(p), working: dayDutyCrew !== null, countedIn: dayDutyCrew }));
  const regularMorning = people.find((p) => p.role === "morning_controller") ?? null;
  let morningPost;
  if (rotation) {
    const holder = byId.get(rotation.employeeId) ?? null;
    morningPost = { holder, status: holder && leaveOf(holder) ? "on_leave" : "held", viaRotation: true, away: null };
  } else if (!regularMorning) morningPost = { holder: null, status: "vacant", viaRotation: false, away: null };
  else {
    const away = assignmentOf(regularMorning);
    morningPost = away?.kind === "shift_cover" ? { holder: null, status: "coverage_required", viaRotation: false, away } : { holder: regularMorning, status: leaveOf(regularMorning) ? "on_leave" : "held", viaRotation: false, away: null };
  }
  const workingCrews = crews.filter((c) => c.working);
  const overall = worst(workingCrews.map((c) => c.status));
  const anyShortage = workingCrews.some((c) => c.confirmedShortage);
  const anyPending = workingCrews.some((c) => c.pending.length > 0);
  const finalStatus = anyShortage ? "red" : anyPending ? null : overall;
  const provisionalStatus = worst(workingCrews.map((c) => c.provisionalStatus));
  const counts = {
    confirmedShortage: workingCrews.filter((c) => c.confirmedShortage).length,
    coverageRequired: workingCrews.filter((c) => c.pending.includes("coverage_required")).length,
    dataIncomplete: workingCrews.filter((c) => c.pending.includes("data_incomplete")).length,
    unresolvedWarnings: crews.reduce((n, c) => n + c.unresolved.length, 0) + dayStaff.filter((s) => s.unresolved).length + dayDuty.filter((s) => s.unresolved).length,
    morningCoverageRequired: morningPost.status === "coverage_required" ? 1 : 0
  };
  return { date, rules, crews, dayStaff, dayDuty, morningPost, overall, finalStatus, provisionalStatus, noBuffer: finalStatus === "amber", counts };
}
function evaluateRange(from, to, people, absences, rules = FULL_OPERATION, assignments = []) {
  const out = [];
  for (let d = from; d <= to; ) {
    out.push(evaluateDay(d, people, absences, rules, assignments));
    const next = /* @__PURE__ */ new Date(d + "T00:00:00Z");
    next.setUTCDate(next.getUTCDate() + 1);
    d = next.toISOString().slice(0, 10);
  }
  return out;
}

// src/core/shiftAlerts/index.ts
var SHIFT_CODES = ["M", "A", "N"];
var DEFAULT_SHIFT_ALERTS = { enabled: true, leadMinutes: 15, tz: "Asia/Kuwait", starts: { M: "06:00", A: "14:00", N: "22:00" } };
var minutesOf = (hhmm) => {
  const [h, m] = hhmm.split(":").map(Number);
  return h * 60 + (m || 0);
};
function zonedNow(ms, tz) {
  const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: tz, hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).formatToParts(new Date(ms)).map((x) => [x.type, x.value]));
  return { date: `${p.year}-${p.month}-${p.day}`, minutes: Number(p.hour) * 60 + Number(p.minute) };
}
function upcomingStarts(nowMs, s, withinMinutes) {
  const now = zonedNow(nowMs, s.tz);
  const out = [];
  for (const shift of SHIFT_CODES) for (const offset of [0, 1]) {
    const inMinutes = offset * 1440 + minutesOf(s.starts[shift]) - now.minutes;
    if (inMinutes > 0 && inMinutes <= withinMinutes) out.push({ date: offset ? addDaysIso(now.date, 1) : now.date, shift, startsAt: s.starts[shift], inMinutes });
  }
  return out.sort((a, b) => a.inMinutes - b.inMinutes);
}
var dueShifts = (nowMs, s) => upcomingStarts(nowMs, s, s.leadMinutes);
var nextShift = (nowMs, s) => upcomingStarts(nowMs, s, 1440 + 60)[0] ?? null;
function alertText(f) {
  const lead = f.controllers.length ? `Controller in charge: ${f.controllers.join(", ")}` : "No Controller counted for this shift: cover needed";
  return {
    title: `${f.test ? "Test · " : ""}${f.crew} Shift · ${SHIFT_LABEL[f.shift]} starts ${f.startsAt}`,
    body: [lead, f.also?.length ? `Also on shift: ${f.also.join(", ")}` : "", f.short.length ? `Short: ${f.short.join(", ")}` : ""].filter(Boolean).join("\n"),
    tag: `shift-${f.date}-${f.shift}`,
    url: `./?date=${f.date}`
  };
}

// supabase/functions/shift-alerts/supabase-shim.ts
import { createClient } from "npm:@supabase/supabase-js@2";
var serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") ?? "{}").default;
var supabase = createClient(Deno.env.get("SUPABASE_URL"), serviceKey, { auth: { persistSession: false, autoRefreshToken: false } });

// src/data/shutdown.ts
var toMember = (r) => ({
  id: r.id,
  planId: r.plan_id,
  teamId: r.team_id,
  employeeId: r.employee_id,
  slot: r.slot,
  offset: r.day_offset,
  start: r.start_date,
  end: r.end_date,
  area: r.area,
  order: Number(/^S\.No (\d+)/.exec(r.note ?? "")?.[1]) || null
});
async function fetchSdMembers(from, to) {
  const { data, error } = await supabase.from("sd_members").select("*, sd_plans!inner(status)").eq("status", "active").eq("sd_plans.status", "active").lte("start_date", to).gte("end_date", from);
  if (error) throw error;
  return data.map(toMember);
}

// src/core/modes/index.ts
var DEFAULT_MODE = {
  code: FULL_OPERATION.modeCode,
  label: FULL_OPERATION.modeLabel,
  controllerMin: FULL_OPERATION.controllerMin,
  panelMin: FULL_OPERATION.panelMin,
  panelGrade14Min: FULL_OPERATION.panelGrade14Min,
  fieldMin: FULL_OPERATION.fieldMin,
  isDefault: true,
  isActive: true,
  note: null
};
var periodOn = (date, plan) => plan.periods.find((p) => p.status === "active" && p.start <= date && date <= p.end) ?? null;
function modeOn(date, plan) {
  const def = plan.modes.find((m) => m.isDefault) ?? DEFAULT_MODE;
  const p = periodOn(date, plan);
  return p && plan.modes.find((m) => m.code === p.modeCode) || def;
}
var rulesFor = (m) => ({
  ...FULL_OPERATION,
  modeCode: m.code,
  modeLabel: m.label,
  controllerMin: m.controllerMin,
  panelMin: m.panelMin,
  panelGrade14Min: m.panelGrade14Min,
  fieldMin: m.fieldMin
});
function rulesByDate(plan) {
  const cache = /* @__PURE__ */ new Map();
  return (date) => {
    const m = modeOn(date, plan);
    let r = cache.get(m.code);
    if (!r) {
      r = rulesFor(m);
      cache.set(m.code, r);
    }
    return r;
  };
}

// src/data/modes.ts
var toMode = (r) => ({ code: r.code, label: r.label, controllerMin: r.controller_min, panelMin: r.panel_min, panelGrade14Min: r.panel_grade14_min, fieldMin: r.field_min, isDefault: r.is_default, isActive: r.is_active, note: r.note });
var toPeriod = (r) => ({ id: r.id, modeCode: r.mode_code, start: r.start_date, end: r.end_date, note: r.note, status: r.status });
async function fetchOperationPlan(from, to) {
  let pq = supabase.from("operation_periods").select("*").order("start_date");
  if (from && to) pq = pq.eq("status", "active").lte("start_date", to).gte("end_date", from);
  const [m, p] = await Promise.all([supabase.from("operating_modes").select("*").order("sort_order").order("label"), pq]);
  if (m.error) throw m.error;
  if (p.error) throw p.error;
  const periods = p.data;
  return { plan: { modes: m.data.map(toMode), periods: periods.map(toPeriod) }, periods };
}

// src/data/controllers.ts
var toMpAssignment = (a) => ({ id: a.id, kind: a.kind, employeeId: a.employee_id, crew: a.crew_code, start: a.start_date, end: a.end_date, coversEmployeeId: a.covers_employee_id });

// src/data/manpower.ts
var ROLES = ["controller", "vr_controller", "morning_controller", "panel_operator", "field_operator"];
function toMpPerson(r) {
  return {
    id: r.id,
    employeeNumber: r.employee_number,
    name: r.display_name,
    grade: r.grade,
    role: ROLES.includes(r.position_code) ? r.position_code : null,
    crew: r.crew_code ?? null,
    employmentType: r.employment_type,
    takeCharge: r.take_charge_status,
    panelQualified: r.panel_operator_status,
    actingController: r.acting_controller_status
  };
}
function toMpAbsence(l) {
  return {
    id: l.id,
    employeeId: l.employee_id,
    start: l.start_date,
    end: l.end_date,
    status: l.status,
    typeCode: l.absence_type_code,
    typeLabel: l.absence_types?.label ?? (l.status === "unresolved" ? "Unresolved absence" : null),
    typeShort: l.absence_types?.short_code ?? null,
    sourceRef: l.source_ref,
    inCurrentPlan: l.in_current_plan,
    oracle: l.oracle_status
  };
}
async function fetchManpowerInputs(from, to) {
  const [dir, lv, ca, ra, mv, op, sd] = await Promise.all([
    supabase.from("employee_directory_v").select("*").eq("in_unit12_scope", true).eq("is_active", true),
    supabase.from("leave_records").select("id,employee_id,start_date,end_date,status,absence_type_code,source_ref,in_current_plan,oracle_status,absence_types(label,short_code)").eq("in_current_plan", true).in("status", ["approved", "planned", "unresolved"]).lte("start_date", to).gte("end_date", from),
    supabase.from("controller_assignments").select("*").eq("status", "active").lte("start_date", to).gte("end_date", from),
    supabase.from("employee_role_assignments").select("employee_id,effective_from,effective_to,positions(code),crews(code)").limit(5e3),
    supabase.from("crew_movements").select("employee_id,start_date,end_date,to_crew,kind").eq("status", "active").in("kind", ["temporary", "placement"]).lte("start_date", to).or(`end_date.is.null,end_date.gte.${from}`),
    fetchOperationPlan(from, to),
    fetchSdMembers(from, to)
  ]);
  const err = [dir, lv, ca, ra, mv].find((r) => r.error)?.error;
  if (err) throw err;
  const history = /* @__PURE__ */ new Map();
  for (const r of ra.data) {
    const role = ROLES.includes(r.positions?.code) ? r.positions.code : null;
    history.set(r.employee_id, [...history.get(r.employee_id) ?? [], { from: r.effective_from, to: r.effective_to, role, crew: r.crews?.code ?? null }]);
  }
  const moves = /* @__PURE__ */ new Map();
  for (const m of mv.data) moves.set(m.employee_id, [...moves.get(m.employee_id) ?? [], { start: m.start_date, end: m.end_date, crew: m.to_crew, kind: m.kind }]);
  const roleOf = new Map(dir.data.map((r) => [r.id, r.position_code]));
  const sdAssignments = [];
  for (const m of sd) {
    if (["controller", "vr_controller", "morning_controller"].includes(roleOf.get(m.employeeId) ?? "")) sdAssignments.push({ id: `sd-${m.id}`, kind: "sd_team", employeeId: m.employeeId, crew: null, start: m.start, end: m.end });
    else moves.set(m.employeeId, [...moves.get(m.employeeId) ?? [], { start: m.start, end: m.end, crew: SD_TEAM, kind: "sd" }]);
  }
  const people = dir.data.map((r) => ({ ...toMpPerson(r), history: history.get(r.id), moves: moves.get(r.id) }));
  return { people, absences: lv.data.map(toMpAbsence), assignments: [...ca.data.map(toMpAssignment), ...sdAssignments], plan: op.plan, rules: rulesByDate(op.plan) };
}

// supabase/functions/shift-alerts/main.ts
var CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-cron-secret",
  "Access-Control-Allow-Methods": "POST, OPTIONS"
};
var reply = (status, body) => new Response(JSON.stringify(body), { status, headers: { ...CORS, "Content-Type": "application/json" } });
var APP_URL = "https://alalramadhan-kuwait.github.io/manpower-control/";
async function config() {
  const { data, error } = await supabase.from("push_config").select("vapid_public,vapid_private,cron_secret").eq("id", true).single();
  if (error) throw error;
  const c = data;
  if (!c.vapid_public || !c.vapid_private) throw new Error("Push keys are not set up (push_config).");
  webpush.setVapidDetails(APP_URL, c.vapid_public, c.vapid_private);
  return c;
}
async function settings() {
  const { data, error } = await supabase.from("shift_alert_settings").select("*").eq("id", true).maybeSingle();
  if (error) throw error;
  if (!data) return DEFAULT_SHIFT_ALERTS;
  const t = (v) => String(v).slice(0, 5);
  return { enabled: data.enabled, leadMinutes: data.lead_minutes, tz: data.tz, starts: { M: t(data.morning_start), A: t(data.afternoon_start), N: t(data.night_start) } };
}
async function factsFor(s, test = false) {
  const inputs = await fetchManpowerInputs(addDaysIso(s.date, -1), addDaysIso(s.date, 1));
  const day = evaluateRange(s.date, s.date, inputs.people, inputs.absences, inputs.rules, inputs.assignments)[0];
  const crew = crewsByShift(s.date)[s.shift];
  const cd = day.crews.find((c) => c.crew === crew);
  const counted = cd.controller.counted;
  const own = counted.filter((p) => p.role === "controller");
  const lead = own.length ? own : counted;
  const name = (p) => p.role === "vr_controller" ? `${p.name} (VR)` : p.name;
  return {
    crew,
    shift: s.shift,
    date: s.date,
    startsAt: s.startsAt,
    test,
    controllers: lead.map(name),
    also: counted.filter((p) => !lead.includes(p)).map(name),
    short: [cd.controller, cd.panel, cd.field].filter((p) => p.finding === "shortage").map((p) => `${p.label} ${p.count} of ${p.min}`)
  };
}
async function send(subs, payload) {
  const body = JSON.stringify(payload);
  const results = await Promise.allSettled(subs.map((s) => webpush.sendNotification({ endpoint: s.endpoint, keys: { p256dh: s.p256dh, auth: s.auth } }, body, { TTL: 600, urgency: "high" })));
  const gone = [];
  results.forEach((r, i) => {
    if (r.status === "rejected") {
      const code = r.reason.statusCode;
      console.error("push failed", code, String(r.reason.message ?? r.reason).slice(0, 200));
      if (code === 404 || code === 410) gone.push(subs[i].id);
    }
  });
  if (gone.length) await supabase.from("push_subscriptions").delete().in("id", gone);
  const sent = results.filter((r) => r.status === "fulfilled").length;
  if (sent) await supabase.from("push_subscriptions").update({ last_sent_at: (/* @__PURE__ */ new Date()).toISOString() }).in("id", subs.filter((_, i) => results[i].status === "fulfilled").map((s) => s.id));
  return { sent, failed: results.length - sent };
}
async function allSubs() {
  const { data, error } = await supabase.from("push_subscriptions").select("id,user_id,endpoint,p256dh,auth");
  if (error) throw error;
  return data;
}
async function runCron() {
  const s = await settings();
  if (!s.enabled) return { enabled: false };
  const due = dueShifts(Date.now(), s);
  if (!due.length) return { due: 0 };
  const subs = await allSubs();
  if (!subs.length) return { due: due.length, phones: 0 };
  const out = [];
  for (const d of due) {
    const claim = await supabase.from("shift_alert_log").upsert({ shift_date: d.date, shift: d.shift }, { onConflict: "shift_date,shift", ignoreDuplicates: true }).select();
    if (claim.error) throw claim.error;
    if (!claim.data?.length) {
      out.push({ ...d, skipped: "already sent" });
      continue;
    }
    const f = await factsFor(d);
    const r = await send(subs, alertText(f));
    await supabase.from("shift_alert_log").update({ crew: f.crew, sent: r.sent, failed: r.failed }).eq("shift_date", d.date).eq("shift", d.shift);
    out.push({ ...d, crew: f.crew, ...r });
  }
  return { due: due.length, phones: subs.length, out };
}
async function staffUser(req) {
  const token = (req.headers.get("Authorization") ?? "").replace(/^Bearer\s+/i, "");
  if (!token) return null;
  const { data, error } = await supabase.auth.getUser(token);
  if (error || !data.user) return null;
  const { data: p } = await supabase.from("user_profiles").select("role_code,is_active").eq("auth_user_id", data.user.id).maybeSingle();
  return p?.is_active && ["section_head", "manpower_coordinator"].includes(p.role_code) ? data.user.id : null;
}
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  try {
    const cfg = await config();
    const secret = req.headers.get("x-cron-secret");
    if (secret) {
      if (secret !== cfg.cron_secret) return reply(401, { error: "Not allowed." });
      const b = await req.json().catch(() => ({}));
      if (b.action !== "preview") return reply(200, await runCron());
      const next2 = nextShift(b.at ? Date.parse(b.at) : Date.now(), await settings());
      return reply(200, next2 ? { next: next2, alert: alertText(await factsFor(next2)) } : { error: "No shift found." });
    }
    const user = await staffUser(req);
    if (!user) return reply(401, { error: "Sign in as the Section Head or the Manpower Coordinator." });
    const body = await req.json().catch(() => ({}));
    const next = nextShift(Date.now(), await settings());
    if (!next) return reply(200, { error: "No shift found." });
    if (body.action === "preview") return reply(200, { next, alert: alertText(await factsFor(next)) });
    if (body.action === "test") {
      const mine = (await allSubs()).filter((s) => s.user_id === user);
      if (!mine.length) return reply(200, { error: "This phone is not subscribed yet." });
      return reply(200, { next, ...await send(mine, alertText(await factsFor(next, true))) });
    }
    return reply(400, { error: "Unknown action." });
  } catch (e) {
    console.error(e);
    return reply(500, { error: String(e.message ?? e) });
  }
});
